### PR TITLE
Minor API, Documentation, and Testing Environment Improvements

### PR DESCRIPTION
**Pull request by matttproud**
Hi, @jmhodges!  I've used Levigo quite a bit, and I want to volunteer a couple of cleanups to improve user experience.  I've kept each change atomic as a separate self-standing commit; but if you want, I can squash them together into one.  For ease and speed of review, I have included the rationales in each commit log message.

A major improvement is the inclusion of automated testing with Travis, which works: [Build Status](https://travis-ci.org/matttproud/levigo).

The only thing you would need to do, should you accept this pull request, is to manually enable Travis CI for jmhodges/levigo in your project setup.  Nothing in this pull request relies on my configuration, except for this pull request description.  :-)

### CODE REVIEW

**Comment by jmhodges** [comment]
Whoa, I am so sorry for not seeing this earlier. I'm looking at it now.

**Comment by jmhodges** [comment]
Oh, I remember this now. Please undo the API changes you made and please break this up into separate changes. It's much too large to review at once.

**Comment by matttproud** [comment]
Sure thing!

**Comment by matttproud** [comment]
Once those pull requests are merged, I can create child pulls for c5b9fd6 and b39f747 and 2b57481.

**Comment by matttproud** [comment]
Cool, then all that remains (outside of API changes) are #32 and #36.

**Comment by jmhodges** [comment]
Thanks for the work on this. We've gotten all of the backwards compatible code of this PR! Unfortunately, the API breaks will have to remain unmerged.

**Pull request closed without merging**
